apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  labels:
    app: emptydir-demo
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "while true; do ls -la /data; sleep 20; done"]
      volumeMounts:
        - name: scratch
          mountPath: /data
  volumes:
    - name: scratch
      emptyDir: {}
