apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: development
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-and-memory
  namespace: dev
spec:
  limits:
    - default:
        cpu: 1
        memory: 512Mi
      defaultRequest:
        cpu: 0.5
        memory: 256Mi
      type: Container

---
apiVersion: v1
kind: Pod
metadata:
  name: default-cpu-and-memory-pod
  namespace: dev
spec:
  containers:
    - name: cont1
      image: nginx:alpine
      