apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: production
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-limitrange
  namespace: prod
spec:
  limits:
    - max:
        cpu: 1
        memory: 1Gi
      min:
        cpu: 0.1
        memory: 500Mi
      type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: min-max-limitrange-pod
  namespace: prod
spec:
  containers:
    - name: cont1
      image: nginx:alpine
      resources:
        limits:
          cpu: 0.5
          memory: 500Mi
        requests:
          cpu: 0.3
          memory: 500Mi